ALTER TABLE authors OWNER TO dev_user;
ALTER TABLE books OWNER TO dev_user;
GRANT ALL PRIVILEGES ON DATABASE learn_sql TO dev_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dev_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO dev_user;
